<!-- Automagically generated by 'jsdocs' -->
<template>
  <div id="contact-page">
    <div class="contact-page row">
      <ContactBlock :contact="content.contact"/>
    </div>
  </div>
</template>

<script>
import ContactBlock from "./../components/ContactBlock";

export default {
  name: "Gallery",
  components: {
    ContactBlock
  },
  props: ["content"],
  meta() {
    return {
      title: "Contact Us",
      description: "This is the meta description for the contact page"
    };
  },
  data: function() {
    return {};
  },
  methods: {}
};
</script>

<style>
* {
  box-sizing: border-box;
}
</style>
