<!-- Automagically generated by 'jsdocs' -->
<template>
  <div id="gallery-page">
    <div class="gallery-page row">
      <GalleryBlock :photos="content.photos.data"/>
    </div>
  </div>
</template>

<script>
import GalleryBlock from "./../components/GalleryBlock";

export default {
  name: "Gallery",
  components: {
    GalleryBlock
  },
  props: ["content"],
  meta() {
    return {
      title: "Gallery",
      description: "This is the meta description for the gallery page"
    };
  },
  data: function() {
    return {};
  },
  methods: {}
};
</script>

<style>
* {
  box-sizing: border-box;
}
</style>
