<!-- Automagically generated by 'jsdocs' -->
<template>
  <div id="home-page">
    <div class="home-page row">
      <Banner :basic="content.basic" :contact="content.contact"/>
      <ContentBlock :basic="content.basic" :photos="content.photos" reverse="true"/>
      <MenuBlock :menus="content.menus.data"/>
      <ReviewBlock :reviews="content.reviews.data"/>
      <GalleryBlock :photos="content.photos.data" max="8" more="true"/>
      <ContactBlock :contact="content.contact"/>
    </div>
  </div>
</template>

<script>
import Banner from "./../components/Banner";
import ContentBlock from "./../components/ContentBlock";
import MenuBlock from "./../components/MenuBlock";
import ReviewBlock from "./../components/ReviewBlock";
import GalleryBlock from "./../components/GalleryBlock";
import ContactBlock from "./../components/ContactBlock";

export default {
  name: "Home",
  components: {
    Banner,
    ContentBlock,
    MenuBlock,
    ReviewBlock,
    GalleryBlock,
    ContactBlock
  },
  props: ["content"],
  meta() {
    return {
      title: "Home",
      description: "This is the meta description for the home page"
    };
  },
  data: function() {
    return {};
  },
  methods: {}
};
</script>

<style>
* {
  box-sizing: border-box;
}
</style>
