<!-- Automagically generated by 'jsdocs' -->
<template>
  <div id="menu-page">
    <div class="menu-page row">
      <h1>Menu</h1>
      <div class="nav-items">
        <b-nav pills align="center">
          <b-nav-item
            v-for="item in navItems"
            :active="selected === item.id"
            :key="item.id"
            @click="() => selectMenu(item.id)"
          >{{item.text}}</b-nav-item>
        </b-nav>
      </div>
      <div class="row">
        <div
          class="col-xs-12 col-sm-6 col-md-4 col-lg-4 mt-4"
          v-for="(menu, index) in menuItems"
          :key="index"
        >
          <b-card
            :title="menu.title"
            :sub-title="menu.description"
            :img-src="menu.picture"
            :img-alt="menu.title"
            img-fluid
            img-top
          >
            <span class="price">Price: {{menu.price}}</span>
          </b-card>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "Menu",
  components: {},
  props: ["content"],
  meta() {
    return {
      title: "Menu",
      description: "This is the meta description for the menu page"
    };
  },
  data: function() {
    return {
      selected: null
    };
  },
  methods: {
    capitalize: string => {
      return string.charAt(0).toUpperCase() + string.slice(1);
    },
    selectMenu: function(selected) {
      this.selected = selected;
    }
  },
  mounted() {
    let selected = this.$route.query.item || this.navItems[0].id;
    this.selected = selected;
  },
  computed: {
    menuItems: function() {
      let menus = this.content.menus.data || [];
      let selected = this.selected || this.navItems[0].id;
      menus = menus.filter(menu => {
        if (selected === "all") {
          return menu.meal;
        }
        return menu.meal === selected;
      });
      return menus || [];
    },
    navItems: function() {
      let navs = this.content.menus.data || [];
      navs = navs.map(menu => {
        return {
          id: menu.meal,
          text: this.capitalize(menu.meal)
        };
      });
      navs.push({
        id: "all",
        text: "All Food"
      });
      return navs || [];
    }
  }
};
</script>

<style lang="scss">
.nav-item {
  a {
    color: var(--gray-dark);
  }
}

.nav-pills .nav-link.active {
  background-color: var(--gray-dark);
}
</style>


<style lang="scss" scoped>
.menu-page {
  width: 100%;
  padding: 40px 40px;

  .row {
    width: 100%;
  }

  .nav-items {
    margin: 20px auto;
    width: 100%;
  }

  h1 {
    width: 100%;
    font-size: 60px;
    text-align: center;
  }
}
</style>
